-- MySQL Script generated by MySQL Workbench
-- Mon Nov 22 09:22:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Time` (
  `TimeID` INT NOT NULL,
  `OrderStatu` VARCHAR(45) NULL,
  `CurrentDay` VARCHAR(45) NULL,
  `Month` VARCHAR(45) NULL,
  `Year` VARCHAR(45) NULL,
  PRIMARY KEY (`TimeID`),
  CONSTRAINT `Time`
    FOREIGN KEY (`TimeID`)
    REFERENCES `mydb`.`Size` (`SizeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `PaymentID` INT NOT NULL,
  `CustomerName` VARCHAR(45) NULL,
  `CardNumber` VARCHAR(45) NULL,
  `CVVNumber` VARCHAR(45) NULL,
  `TimeID` INT NULL,
  PRIMARY KEY (`PaymentID`),
  INDEX `Payment_idx` (`TimeID` ASC) VISIBLE,
  CONSTRAINT `Payment`
    FOREIGN KEY (`TimeID`)
    REFERENCES `mydb`.`Time` (`TimeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Size` (
  `SizeID` INT NOT NULL AUTO_INCREMENT,
  `OrderSize` VARCHAR(45) NULL,
  `PaymentID` INT NULL,
  PRIMARY KEY (`SizeID`),
  INDEX `Size_idx` (`PaymentID` ASC) VISIBLE,
  CONSTRAINT `Size`
    FOREIGN KEY (`PaymentID`)
    REFERENCES `mydb`.`Payment` (`PaymentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `OrderNumber` VARCHAR(45) NULL,
  `OrderDate` VARCHAR(45) NULL,
  `OrderQuantity` VARCHAR(45) NULL,
  `SizeID` INT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `Order_idx` (`SizeID` ASC) VISIBLE,
  CONSTRAINT `Order`
    FOREIGN KEY (`SizeID`)
    REFERENCES `mydb`.`Size` (`SizeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `MenuID` INT NOT NULL,
  `MenuCode` VARCHAR(45) NULL,
  `ItemPrice` VARCHAR(45) NULL,
  `OrderID` INT NULL,
  PRIMARY KEY (`MenuID`),
  INDEX `Menu_idx` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `Menu`
    FOREIGN KEY (`OrderID`)
    REFERENCES `mydb`.`Order` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `LocationID` INT NOT NULL AUTO_INCREMENT,
  `AddressLine1` VARCHAR(45) NULL,
  `AddressLine2` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `Territory` VARCHAR(45) NULL,
  `MenuID` INT NULL,
  PRIMARY KEY (`LocationID`),
  INDEX `Location_idx` (`MenuID` ASC) VISIBLE,
  CONSTRAINT `Location`
    FOREIGN KEY (`MenuID`)
    REFERENCES `mydb`.`Menu` (`MenuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `Customerscol` VARCHAR(45) NULL,
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `Customer Username` VARCHAR(45) NULL,
  `CustomerPassword` VARCHAR(45) NULL,
  `CustomerName` VARCHAR(45) NULL,
  `LocationID` INT NULL,
  PRIMARY KEY (`CustomerID`),
  INDEX `Customers_idx` (`LocationID` ASC) VISIBLE,
  CONSTRAINT `Customers`
    FOREIGN KEY (`LocationID`)
    REFERENCES `mydb`.`Location` (`LocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
